### PR TITLE
French

### PR DESCRIPTION
**Pull request by MaraScott**
Hi,

I played a bit with your code and move it to php.

All text are in french.

Let me know if you have any remarks.

### CODE REVIEW

**Comment by siamkreative** [comment]
Merci @davask ! I'll look into this.

Why switching the PHP by the way? The main reason why I wanted front-end only is so that I could host it for free on a fast hosting provider called [Surge](https://surge.sh/).

**Comment by MaraScott** [comment]
Are you french ?

I tagged the latest static version, in case you want it.

I switch to php as I want to make it more dynamic and at some point store some data in mysql as well.
I d like to bring some language settings to.

That s not your initial design but I wanted to share what I did from your previous version.

Cheers

**Comment by siamkreative** [comment]
Yup, I'm French.

I will get back to you on this asap.

**Comment by MaraScott** [comment]
Je suis francais aussi ;)

**Comment by MaraScott** [comment]
D ailleurs j ai pousse sur master par defaut mais je prefererai pousser sur une branche independante vu que je m eloigne du design original.
Bonne fin de journee

**Pull request closed without merging**
